service: wuxiaBackend
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
functions:
  app:
    handler: server.run
    events:
    - http:
        path: /
        method: ANY
        cors: true
    - http:
        path: /{proxy+}
        method: ANY
        cors: true
resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Users
    NovelsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: Novels

custom:
  serverless-offline:
    httpPort: 3001
plugins:
  - serverless-offline
