service: wuxia_backend
provider:
  name: aws
  runtime: nodejs10.x
functions:
  app:
    handler: server.run
    events:
    - http:
        path: /
        method: ANY
        cors: false
    - http:
        path: /{proxy+}
        method: ANY
        cors: false
plugins:
  - serverless-offline
